require: rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  ExcludedMethods:
    - it
    - describe
    - before

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 10
